---
title: "ica-wrangling"
format: html
---

```{r}
# Load tidyverse & data
library(tidyverse)
elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")
```
```{r}
# Get a background map
library(socviz)
data(county_map)

# Make a choropleth map
library(RColorBrewer)  # For the color scale
library(ggthemes) # For theme_map
elections |> 
  mutate(county_fips = as.character(county_fips)) |> 
  mutate(county_fips = 
           ifelse(nchar(county_fips) == 4, paste0("0", county_fips), county_fips)) |> 
  ggplot(aes(map_id = county_fips, fill = cut(repub_pct_20, breaks = seq(0, 100, by = 10)))) +
    geom_map(map = county_map) +
    scale_fill_manual(values = rev(brewer.pal(10, "RdBu")), name = "% Republican") +
    expand_limits(x = county_map$long, y = county_map$lat)  + 
    theme_map() +
    theme(legend.position = "right") + 
    coord_equal()
```
```{r}
# Define elections_small
elections_small <- elections |>
select(state_name, county_name, total_votes_20, repub_pct_20, dem_pct_20, total_votes_16, dem_pct_16)

```
```{r}
head (elections_small)
```
```{r}
# Keep only data on counties in Hawaii
elections_small|>
filter(county_name == "Hawaii County")
```
```{r}
 # What does this do?
elections_small |> 
filter(state_name %in% c("Hawaii", "Delaware"))
```
```{r}
elections_small |> 
  filter(repub_pct_20 > "93.97")
```
```{r}
elections_small |> 
  filter(repub_pct_20 >= "93.97")
```

```{r}
elections_small |> 
  filter(state_name == "Texas")|> 
  filter(dem_pct_20 > 65)

```
```{r}
elections_small |> 
  filter(state_name == "Texas", dem_pct_20 > 65)
```
```{r}
elections_small |> 
  arrange(repub_pct_20) 
  
```
```{r}
elections_small |>
  arrange(desc(repub_pct_20))
```
```{r}
# What did this code do?
elections_small |> 
  mutate(diff_20 = repub_pct_20 - dem_pct_20) |> 
  head()
```
```{r}
# What did this code do?
 elections_small |> 
   mutate(repub_votes_20 = round(total_votes_20 * repub_pct_20/100)) |> 
   head()
```

